---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true
  network:
    - ["forwarded_port", {guest: 27017, host: 27017, auto_correct: true}]
    - ["private_network", {ip: "192.168.33.10"}]
provisioner: chef_zero

platforms:
  - name: centos-6.4

# driver:
#  name: ec2
#  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY'] %>
#  aws_secret_access_key: <%= ENV['AWS_SECRET_KEY'] %>
#  aws_ssh_key_id: <%= ENV['AWS_SSH_KEY_ID'] %>
#  ssh_key: <%= File.expand_path('~/.ssh/id_rsa') %>
#  security_group_ids: ["sg-1a2b3c4d"]
#  region: us-west-2
#  availability_zone: us-west-2b
#  require_chef_omnibus: true

# platforms:
#   - name: centos-6.3
#    driver:
#      image_id: ami-ef5ff086
 #     username: ec2-user

suites:
  - name: default
    run_list:
      - recipe[lm-mongodb::install]
    attributes:
